import Head from "next/head";
import FontSize from "../components/FontSize";
import FontSizeSol from "../components/solutions/FontSizeSol";
import SearchBar from "../components/SearchBar";
import SearchBarSol from "../components/solutions/SearchBarSol";
import Theme from "../components/Theme";
import ThemeSol from "../components/solutions/ThemeSol";
import Todos from "../components/Todos";
import TodosSol from "../components/solutions/TodosSol";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Hooks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>01. Theme</h2>
        <div className={styles.container}>
          <Theme />
          <ThemeSol />
        </div>

        <h2 className={styles.title}>02. FontSize</h2>
        <div className={styles.container}>
          <FontSize />
          <FontSizeSol />
        </div>

        <h2 className={styles.title}>03. Todos</h2>
        <div className={styles.container}>
          <Todos />
          <TodosSol />
        </div>

        <h2 className={styles.title}>04. SearchBar</h2>
        <div className={styles.container}>
          <SearchBar />
          <SearchBarSol />
        </div>
      </main>
    </div>
  );
}
